### PR TITLE
Move filemanager to `edl` repo.

### PR DESCRIPTION
**Pull request by gongweibao**
Fix https://github.com/PaddlePaddle/Paddle/issues/9146

### CODE REVIEW

**Review by typhoonzero — APPROVED** [review]
LGTM++

**Comment by helinwang** [comment]
@gongweibao want to discuss with you: does file manager belong to EDL or Paddle cloud? To me, EDL means a Kubernetes controller that automatically scales the training job. Paddle Cloud is the "front end" that post the job configuration (a Kubernets custom resource), and also doing the file management.

**Comment by typhoonzero** [comment]
Are we going to deprecate `cloud` repo in the future? If not, I think it's better to put "FileManager" and "Jupiter Notebook web site" in that repo, and make it small.

**Comment by helinwang** [comment]
@typhoonzero I don't think we are going to deprecate `cloud` repo. Agree, we should make `edl` small.

**Pull request merged**
